parameters:
    da.stat.handler.class: Da\StatBundle\Handler\StatHandler

services:
    # Handlers
    da.stat.handler:
        class: %da.stat.handler.class%
        arguments: [@router, @translator, %da.stat.config.stat%, %da.stat.config.assemblies%, %da.stat.config.menu%]

    # Renderers
    da.stat.renderer.chart:
        class: Da\StatBundle\Renderer\ChartRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.piechart:
        class: Da\StatBundle\Renderer\PieChartRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.polarchart:
        class: Da\StatBundle\Renderer\PolarChartRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.map:
        class: Da\StatBundle\Renderer\MapRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.table:
        class: Da\StatBundle\Renderer\TableRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.stackedbarchart:
        class: Da\StatBundle\Renderer\StackedBarChartRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.stackedcolumnchart:
        class: Da\StatBundle\Renderer\StackedColumnChartRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    da.stat.renderer.barchart:
        class: Da\StatBundle\Renderer\BarRenderer
        arguments: [@translator]
        tags:
            - { name: da.stat.renderer }

    # Filters
    da.stat.filter.date:
        class: Da\StatBundle\Filter\DateFilter
        arguments: []
        tags:
            - { name: da.stat.filter }