parameters:
    da_stat.mediator.class: Da\StatBundle\Mediator\StatMediator
    da_stat.displayer.class: Da\StatBundle\Twig\StatDisplayer
    da_stat.twig_extension.class: Da\StatBundle\Twig\StatExtension

services:
    da_stat.mediator:
        class: %da_stat.mediator.class%
        arguments: [@router, @translator, %da_stat.stat%, %da_stat.assemblies%, %da_stat.menu%]

    da_stat.aggregator:
        abstract: true
        arguments: [@translator, @security.context]

    da_stat.displayer:
        class: %da_stat.displayer.class%
        arguments: [@templating, @da_stat.mediator]

    da_stat.twig_extension:
        class: %da_stat.twig_extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }