parameters:
    da_stat.mediator.class: Da\StatBundle\Handler\StatHandler

services:
    da_stat.mediator:
        class: %da_stat.mediator.class%
        arguments: [@router, @translator, %da_stat.stat%, %da_stat.assemblies%, %da_stat.menu%]

    da_stat.aggregator:
        abstract: true
        arguments: [@translator, @security_context]